### ISSUE TITLE
brew package?

### ISSUE THREAD

**Issue by sg-s** [KeyboardFire/mkcast#2]
Hi, any plans for making a [brew](http://brew.sh) package?

**Comment by bruno-** [comment]
yes please :+1:

**Comment by VinSpee** [comment]
This would be ideal

**Comment by rmoriz** [comment]
It probably won't work on OSX as it relies on gnome and X

**Comment by tckmn** [comment]
Unfortunately this will not work on OS X, since it's using `xdpyinfo`, `wmctrl`, etc. I don't have access to any OS X machines, but do feel free to suggest a pull request that makes it work!
