### ISSUE TITLE
Suggestion: get rid of the duration argument

### ISSUE THREAD

**Issue by sagotsky** [KeyboardFire/mkcast#3]
Byzanz's duration argument bothers me every time I have to use it.  Here's how I got rid of it in my own script: https://github.com/sagotsky/.dotfiles/blob/master/scripts/byzanz-gif.sh

tl;dr use the --exec flag instead of duration to end byzanz via shell commands.  The shell commands I use check if a dzen is still running.  Instead I'd suggestion spawning the terminal to record and having exec check if that's still up.  When someone ctrl-d's out of it, end the recording.

**Comment by tckmn** [comment]
Done! `newcast` now finishes recording when the terminal it spawns exits. Thanks for the idea!
