### ISSUE TITLE
webm support

### ISSUE THREAD

**Issue by zQueal** [KeyboardFire/mkcast#7]
GIF is great. I think we all know that. However, it's old, outdated, and bloated. I'd really love to see webm support for this project.

**Comment by JaredCubilla** [comment]
+1

**Comment by brunowego** [comment]
+1

**Comment by S0yKaf** [comment]
+1

**Comment by tckmn** [comment]
Ugh... I wanted this to be GIF-only, but fine. New syntax:

```
$ newcast -o out.webm  # also supports ogg/ogv
```

**Comment by brunowego** [comment]
:+1:
