### ISSUE TITLE
Setup script results in broken symlink Ubuntu 14.10

### ISSUE THREAD

**Issue by timelf123** [KeyboardFire/mkcast#9]
> ➜  sudo ./setup.sh
> ➜  mkcast
> zsh: too many levels of symbolic links: mkcast

This is what the links look like:

> ➜  ls -la /usr/local/bin/
> drwxr-xr-x  2 root root    4096 Feb  2 11:05 .
> drwxr-xr-x 12 root root    4096 Dec 10 13:24 ..
> lrwxrwxrwx  1 root root       6 Feb  2 11:05 mkcast -> mkcast
> lrwxrwxrwx  1 root root       7 Feb  2 11:05 newcast -> newcast

Does this suggest the links are pointing to themselves?

**Comment by ruslanosipov** [comment]
+1 on this. I just moved my `mkcast` and `newcast` to `$HOME/bin`.

**Comment by TheHippo** [comment]
Had the same issue with Ubuntu 14.04.

**Comment by tckmn** [comment]
Thanks, this is fixed now.
